# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/calculator.ui',
# licensing of 'view/calculator.ui' applies.
#
# Created: Sun Dec  1 22:42:45 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(562, 350))
        MainWindow.setMaximumSize(QtCore.QSize(562, 350))
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("#label_output {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(128, 128, 128);\n"
"    background-color: rgb(128, 128, 128);\n"
"    color: white;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(179, 179, 179);\n"
"    color: white;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: rgb(128, 128, 128);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(215, 213, 216);\n"
"}\n"
"\n"
"QPushButton[cssClass=\"actions\"] {\n"
"    background-color: rgb(244, 199, 0)\n"
"}\n"
"\n"
"QPushButton[cssClass=\"actions\"]:pressed {\n"
"    background-color: rgb(208, 158, 0)\n"
"}\n"
"\n"
"#pushButton_equals {\n"
"    background-color: rgb(204, 204, 204);\n"
"}\n"
"\n"
"#pushButton_equals:pressed {\n"
"    background-color: rgb(179, 179, 179);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_output.sizePolicy().hasHeightForWidth())
        self.label_output.setSizePolicy(sizePolicy)
        self.label_output.setMaximumSize(QtCore.QSize(16777215, 65))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_output.setFont(font)
        self.label_output.setAutoFillBackground(False)
        self.label_output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_output.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_output.setObjectName("label_output")
        self.gridLayout_2.addWidget(self.label_output, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_change_sign = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_change_sign.sizePolicy().hasHeightForWidth())
        self.pushButton_change_sign.setSizePolicy(sizePolicy)
        self.pushButton_change_sign.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_change_sign.setFont(font)
        self.pushButton_change_sign.setStyleSheet("")
        self.pushButton_change_sign.setObjectName("pushButton_change_sign")
        self.gridLayout.addWidget(self.pushButton_change_sign, 1, 6, 1, 1)
        self.pushButton_percentage = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_percentage.sizePolicy().hasHeightForWidth())
        self.pushButton_percentage.setSizePolicy(sizePolicy)
        self.pushButton_percentage.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_percentage.setFont(font)
        self.pushButton_percentage.setStyleSheet("")
        self.pushButton_percentage.setObjectName("pushButton_percentage")
        self.gridLayout.addWidget(self.pushButton_percentage, 2, 6, 1, 1)
        self.pushButton_nine = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_nine.sizePolicy().hasHeightForWidth())
        self.pushButton_nine.setSizePolicy(sizePolicy)
        self.pushButton_nine.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_nine.setFont(font)
        self.pushButton_nine.setStyleSheet("")
        self.pushButton_nine.setObjectName("pushButton_nine")
        self.gridLayout.addWidget(self.pushButton_nine, 0, 2, 1, 1)
        self.pushButton_five = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_five.sizePolicy().hasHeightForWidth())
        self.pushButton_five.setSizePolicy(sizePolicy)
        self.pushButton_five.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_five.setFont(font)
        self.pushButton_five.setStyleSheet("")
        self.pushButton_five.setObjectName("pushButton_five")
        self.gridLayout.addWidget(self.pushButton_five, 1, 1, 1, 1)
        self.pushButton_two = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_two.sizePolicy().hasHeightForWidth())
        self.pushButton_two.setSizePolicy(sizePolicy)
        self.pushButton_two.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_two.setFont(font)
        self.pushButton_two.setStyleSheet("")
        self.pushButton_two.setObjectName("pushButton_two")
        self.gridLayout.addWidget(self.pushButton_two, 2, 1, 1, 1)
        self.pushButton_subtract = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_subtract.sizePolicy().hasHeightForWidth())
        self.pushButton_subtract.setSizePolicy(sizePolicy)
        self.pushButton_subtract.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_subtract.setFont(font)
        self.pushButton_subtract.setStyleSheet("")
        self.pushButton_subtract.setObjectName("pushButton_subtract")
        self.gridLayout.addWidget(self.pushButton_subtract, 2, 4, 1, 1)
        self.pushButton_equals = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_equals.sizePolicy().hasHeightForWidth())
        self.pushButton_equals.setSizePolicy(sizePolicy)
        self.pushButton_equals.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_equals.setFont(font)
        self.pushButton_equals.setStyleSheet("")
        self.pushButton_equals.setDefault(False)
        self.pushButton_equals.setObjectName("pushButton_equals")
        self.gridLayout.addWidget(self.pushButton_equals, 3, 6, 1, 1)
        self.pushButton_multiply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_multiply.sizePolicy().hasHeightForWidth())
        self.pushButton_multiply.setSizePolicy(sizePolicy)
        self.pushButton_multiply.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_multiply.setFont(font)
        self.pushButton_multiply.setStyleSheet("")
        self.pushButton_multiply.setObjectName("pushButton_multiply")
        self.gridLayout.addWidget(self.pushButton_multiply, 1, 4, 1, 1)
        self.pushButton_division = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_division.sizePolicy().hasHeightForWidth())
        self.pushButton_division.setSizePolicy(sizePolicy)
        self.pushButton_division.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_division.setFont(font)
        self.pushButton_division.setStyleSheet("")
        self.pushButton_division.setDefault(False)
        self.pushButton_division.setFlat(False)
        self.pushButton_division.setObjectName("pushButton_division")
        self.gridLayout.addWidget(self.pushButton_division, 0, 4, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add.sizePolicy().hasHeightForWidth())
        self.pushButton_add.setSizePolicy(sizePolicy)
        self.pushButton_add.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("")
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 3, 4, 1, 1)
        self.pushButton_three = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_three.sizePolicy().hasHeightForWidth())
        self.pushButton_three.setSizePolicy(sizePolicy)
        self.pushButton_three.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_three.setFont(font)
        self.pushButton_three.setStyleSheet("")
        self.pushButton_three.setObjectName("pushButton_three")
        self.gridLayout.addWidget(self.pushButton_three, 2, 2, 1, 1)
        self.pushButton_decimal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_decimal.sizePolicy().hasHeightForWidth())
        self.pushButton_decimal.setSizePolicy(sizePolicy)
        self.pushButton_decimal.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_decimal.setFont(font)
        self.pushButton_decimal.setStyleSheet("")
        self.pushButton_decimal.setObjectName("pushButton_decimal")
        self.gridLayout.addWidget(self.pushButton_decimal, 3, 2, 1, 1)
        self.pushButton_one = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_one.sizePolicy().hasHeightForWidth())
        self.pushButton_one.setSizePolicy(sizePolicy)
        self.pushButton_one.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_one.setFont(font)
        self.pushButton_one.setStyleSheet("")
        self.pushButton_one.setObjectName("pushButton_one")
        self.gridLayout.addWidget(self.pushButton_one, 2, 0, 1, 1)
        self.pushButton_seven = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_seven.sizePolicy().hasHeightForWidth())
        self.pushButton_seven.setSizePolicy(sizePolicy)
        self.pushButton_seven.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_seven.setFont(font)
        self.pushButton_seven.setStyleSheet("")
        self.pushButton_seven.setObjectName("pushButton_seven")
        self.gridLayout.addWidget(self.pushButton_seven, 0, 0, 1, 1)
        self.pushButton_six = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_six.sizePolicy().hasHeightForWidth())
        self.pushButton_six.setSizePolicy(sizePolicy)
        self.pushButton_six.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_six.setFont(font)
        self.pushButton_six.setStyleSheet("")
        self.pushButton_six.setObjectName("pushButton_six")
        self.gridLayout.addWidget(self.pushButton_six, 1, 2, 1, 1)
        self.pushButton_eight = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_eight.sizePolicy().hasHeightForWidth())
        self.pushButton_eight.setSizePolicy(sizePolicy)
        self.pushButton_eight.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_eight.setFont(font)
        self.pushButton_eight.setStyleSheet("")
        self.pushButton_eight.setObjectName("pushButton_eight")
        self.gridLayout.addWidget(self.pushButton_eight, 0, 1, 1, 1)
        self.pushButton_four = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_four.sizePolicy().hasHeightForWidth())
        self.pushButton_four.setSizePolicy(sizePolicy)
        self.pushButton_four.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_four.setFont(font)
        self.pushButton_four.setStyleSheet("")
        self.pushButton_four.setObjectName("pushButton_four")
        self.gridLayout.addWidget(self.pushButton_four, 1, 0, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 0, 6, 1, 1)
        self.pushButton_zero = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_zero.sizePolicy().hasHeightForWidth())
        self.pushButton_zero.setSizePolicy(sizePolicy)
        self.pushButton_zero.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_zero.setFont(font)
        self.pushButton_zero.setStyleSheet("")
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.gridLayout.addWidget(self.pushButton_zero, 3, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Heath\'s Calculator", None, -1))
        self.label_output.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.pushButton_change_sign.setText(QtWidgets.QApplication.translate("MainWindow", "+/-", None, -1))
        self.pushButton_change_sign.setProperty("cssClass", QtWidgets.QApplication.translate("MainWindow", "actions", None, -1))
        self.pushButton_percentage.setText(QtWidgets.QApplication.translate("MainWindow", "%", None, -1))
        self.pushButton_percentage.setProperty("cssClass", QtWidgets.QApplication.translate("MainWindow", "actions", None, -1))
        self.pushButton_nine.setText(QtWidgets.QApplication.translate("MainWindow", "9", None, -1))
        self.pushButton_five.setText(QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.pushButton_two.setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.pushButton_subtract.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.pushButton_subtract.setProperty("cssClass", QtWidgets.QApplication.translate("MainWindow", "actions", None, -1))
        self.pushButton_equals.setText(QtWidgets.QApplication.translate("MainWindow", "=", None, -1))
        self.pushButton_multiply.setText(QtWidgets.QApplication.translate("MainWindow", "*", None, -1))
        self.pushButton_multiply.setProperty("cssClass", QtWidgets.QApplication.translate("MainWindow", "actions", None, -1))
        self.pushButton_division.setText(QtWidgets.QApplication.translate("MainWindow", "/", None, -1))
        self.pushButton_division.setProperty("cssClass", QtWidgets.QApplication.translate("MainWindow", "actions", None, -1))
        self.pushButton_add.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.pushButton_add.setProperty("cssClass", QtWidgets.QApplication.translate("MainWindow", "actions", None, -1))
        self.pushButton_three.setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.pushButton_decimal.setText(QtWidgets.QApplication.translate("MainWindow", ".", None, -1))
        self.pushButton_decimal.setProperty("cssClass", QtWidgets.QApplication.translate("MainWindow", "actions", None, -1))
        self.pushButton_one.setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.pushButton_seven.setText(QtWidgets.QApplication.translate("MainWindow", "7", None, -1))
        self.pushButton_six.setText(QtWidgets.QApplication.translate("MainWindow", "6", None, -1))
        self.pushButton_eight.setText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.pushButton_four.setText(QtWidgets.QApplication.translate("MainWindow", "4", None, -1))
        self.pushButton_clear.setText(QtWidgets.QApplication.translate("MainWindow", "C", None, -1))
        self.pushButton_clear.setProperty("cssClass", QtWidgets.QApplication.translate("MainWindow", "actions", None, -1))
        self.pushButton_zero.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))

